- name: Install web server 
  hosts: ec2
  become: yes
  vars:
    webserver: nginx
    webserver_root_dir: /var/www/html
  tasks:
  - name: debug
    debug:
      msg: "The value of webserver {{webserver}}"
  - name: Webserver is isntalled
    package: 
      name: "{{webserver}}"
      state: present
  - name: Webserver is up
    service:
      name: "{{webserver}}"
      state: started
  - name: webserver root directory exists
    file:
      path: "{{webserver_root_dir}}"
      state: directory
  - name: static website is deployed
    uri:
      url: https://raw.githubusercontent.com/abdennour/example-static-website/master/index.html
      dest: "{{webserver_root_dir}}"
  
